"""create daily log tables

Revision ID: 9c8d491c9ddf
Revises: 85842d2e9538
Create Date: 2026-06-18 13:42:50.966503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8d491c9ddf'
down_revision: Union[str, Sequence[str], None] = '85842d2e9538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_flow_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('intensity', sa.Enum('none', 'spotting', 'light', 'medium', 'heavy', name='flowintensity'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('occurred', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_moods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('mood', sa.Enum('happy', 'calm', 'energetic', 'focused', 'sad', 'sensitive', 'irritable', 'anxious', 'tired', 'overwhelmed', name='moodtype'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_sexual_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('occurred', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_sexual_activity')
    op.drop_table('log_moods')
    op.drop_table('log_medications')
    op.drop_table('log_flow_entries')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
